//CATEGORIES
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

//BLOG
export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS';
export const GET_BLOG_LIST_FAIL = 'GET_BLOG_LIST_FAIL';
export const GET_BLOG_LIST_CATEGORIES_SUCCESS = 'GET_BLOG_LIST_CATEGORIES_SUCCESS';
export const GET_BLOG_LIST_CATEGORIES_FAIL = 'GET_BLOG_LIST_CATEGORIES_FAIL';
export const GET_BLOG_SUCCESS= 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAIL= 'GET_BLOG_FAIL';

export const GET_BLOG_PAGINATION_COUNT_SUCCESS = 'GET_BLOG_PAGINATION_COUNT_SUCCESS';
export const GET_BLOG_PAGINATION_COUNT_FAIL = 'GET_BLOG_PAGINATION_COUNT_FAIL';
export const GET_BLOG_PAGINATION_NEXT_SUCCESS = 'GET_BLOG_PAGINATION_NEXT_SUCCESS';
export const GET_BLOG_PAGINATION_NEXT_FAIL = 'GET_BLOG_PAGINATION_NEXT_FAIL';
export const GET_BLOG_PAGINATION_PREVIOUS_SUCCESS = 'GET_BLOG_PAGINATION_PREVIOUS_SUCCESS';
export const GET_BLOG_PAGINATION_PREVIOUS_FAIL = 'GET_BLOG_PAGINATION_PREVIOUS_FAIL';
export const GET_BLOG_PAGINATION_RESULTS_SUCCESS = 'GET_BLOG_PAGINATION_RESULTS_SUCCESS';
export const GET_BLOG_PAGINATION_RESULTS_FAIL = 'GET_BLOG_PAGINATION_RESULTS_FAIL';